name: Build and Test on Push
on:
  push:
  - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and test
      run: cargo build && cargo test -- --ignored -- --nocapture